print("Program starting.\nEstimate how many minutes you spent on programming...")
T1=input("A1_T1: ")
T2=input("A1_T2: ")
T3=input("A1_T3: ")
T4=input("A1_T4: ")
T5=input("A1_T5: ")
T6=input("A1_T6: ")
T7=input("A1_T7: ")
T1=int(T1)
T2=int(T2)
T3=int(T3)
T4=int(T4)
T5=int(T5)
T6=int(T6)
T7=int(T7)
numbers=[T1, T2, T3, T4, T5, T6, T7]
print("In total you spent", sum(numbers), "minutes on programming.")
average=round(sum(numbers)/len(numbers), 2)
integer=round(int(average))
print("Average per task was", average, "and same rounded to the nearest integer", integer, "min.")
print("Program ending.")