print("Program starting.")
brand=input("Insert car brand: ")
model=input("Insert car model: ")
print("Car brand is \"" + brand + "\"", end=" ", sep=" ")
print("and the model is \"" + model + "\".")
print("Program ending.")