print("Program starting.")
first=input("Insert first word: ")
second=input("Insert second word: ")
print("1st word is", len(first), "characters long.")
print("2st word is", len(second), "characters long.")
print("Words together makes one closed compound \'" + first + second + "\'.")
print("Program ending.")